### PR TITLE
added support for multiple joins

### PR DESCRIPTION
**Pull request by brunoguadagnini**

### CODE REVIEW

**Comment by darrachequesne** [comment]
Hi! If not explicitly set, it seems that an `INNER JOIN` clause is created with `path.get()` instead of a `LEFT JOIN`, thus the failure.

Related (I guess): https://github.com/darrachequesne/spring-data-jpa-datatables/issues/7

**Comment by brunoguadagnini** [comment]
Hi @darrachequesne!
Yes, it is the same reported #7! Sorry, I did not see!

**Comment by darrachequesne** [comment]
hi @brunoguadagnini, I can't remember exactly why that didn't work back then, but multiple joins should now properly work :angel: 

Added in https://github.com/darrachequesne/spring-data-jpa-datatables/commit/5ba97e9f160b964c5e10f4a001c6ac093c494fe2

**Comment by brunoguadagnini** [comment]
Great job @darrachequesne! 
Thank you very much!

**Comment by vbura** [comment]
Thank you very much! 
Good job:)

**Pull request closed without merging**
